concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

name: Publish

on:
    push:
        tags:
            - "csv.[0-9]+.[0-9]+.[0-9]+"
    workflow_dispatch:

jobs:
    publish:
        runs-on: macos-latest
        name: Publish
        timeout-minutes: 60
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-java@v4
                name: Setup Java
                with:
                    distribution: 'oracle'
                    java-version: '17'

            -   name: Setup gradle
                uses: gradle/actions/setup-gradle@v4
                with:
                    cache-read-only: ${{ github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' }}
                    gradle-home-cache-includes: |
                        caches
                        notifications
                    gradle-home-cache-cleanup: true
                env:
                    GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

            -   name: Publish credentials
                uses: Infisical/secrets-action@v1.0.9
                with:
                    client-id: ${{ secrets.MACHINE_IDENTITY_CLIENT_ID }}
                    client-secret: ${{ secrets.MACHINE_IDENTITY_CLIENT_SECRET }}
                    env-slug: "prod"
                    project-slug: "secrets"
                    secret-path: "/maven/gradle"
                    domain: https://eu.infisical.com

            -   name: Prepare Release Version
                id: prepareVersion
                run: |
                    RESULT=$(echo ${{ github.ref_name }} | sed 's/csv.//g')
                    echo "VERSION_NAME=$RESULT" >> .env

            -   name: Publish to MavenCentral
                run: ./gradlew :csv:publishToMavenCentral --stacktrace --quiet